name: bayesian-mfa-paper
channels:
  - conda-forge
dependencies:
  - python=3
  - pymc3=3.0
  - scipy=0.19.1
  - numpy=1.12.1
  - pandas
  - matplotlib
  - seaborn
  - mkl-service
  - kiwisolver
  - pip
  - pip:
      - ipysankeywidget
      - floweaver
